name: Video Maker Pro
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: ðŸ› ï¸ Setup environment
      run: |
        echo "ðŸ“¦ Updating package list..."
        sudo apt-get update -q
        echo "âœ… Update complete"
        
    - name: ðŸ”§ Install FFmpeg
      run: |
        echo "ðŸ”§ Installing FFmpeg..."
        sudo apt-get install -y ffmpeg > /dev/null 2>&1
        echo "âœ… FFmpeg installed"
        ffmpeg -version | head -1
        
    - name: ðŸŽ¬ Create video (SAFE METHOD)
      run: |
        echo "ðŸŽ¬ Creating video..."
        # Ø±ÙˆØ´ Ø§ÛŒÙ…Ù† - Ø³Ø§Ø®Øª ÙˆÛŒØ¯ÛŒÙˆÛŒ Ø³Ø§Ø¯Ù‡
        ffmpeg -f lavfi -i color=c=0x2E86AB:s=640x360:d=3 \
               -vf "drawtext=text='GitHub Actions Test':fontcolor=white:fontsize=24:x=20:y=20" \
               -c:v libx264 -pix_fmt yuv420p \
               -frames:v 75 \
               test_video.mp4 2>&1 | tail -5
        
        echo "ðŸ“Š Checking file..."
        ls -lh test_video.mp4
        file test_video.mp4
        
    - name: ðŸ“¤ Upload result
      uses: actions/upload-artifact@v3
      with:
        name: video-result
        path: test_video.mp4
        retention-days: 5
        
    - name: ðŸŽ‰ Success message
      run: |
        echo "========================================"
        echo "âœ… VIDEO CREATION SUCCESSFUL!"
        echo "ðŸ•’ Time: $(date)"
        echo "ðŸ“¦ Artifact: 'video-result'"
        echo "ðŸ“¥ Download from Actions â†’ Artifacts"
        echo "========================================"
